// The datax internode transport: Raft messages, KV batches, cluster
// membership, and admin operations. Payload bodies for KV/join/admin are
// JSON-encoded Go types from pkg/kvpb and pkg/cluster (see those packages);
// Raft messages are raftpb.Message bytes, opaque to the transport.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: datax/v1/transport.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	FromNode int64                  `protobuf:"varint,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	// send_wall is the caller's physical clock (ns since epoch) when the
	// request left.
	SendWall      int64 `protobuf:"varint,2,opt,name=send_wall,json=sendWall,proto3" json:"send_wall,omitempty"`
	Now           *Hlc  `protobuf:"bytes,3,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_datax_v1_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetFromNode() int64 {
	if x != nil {
		return x.FromNode
	}
	return 0
}

func (x *PingRequest) GetSendWall() int64 {
	if x != nil {
		return x.SendWall
	}
	return 0
}

func (x *PingRequest) GetNow() *Hlc {
	if x != nil {
		return x.Now
	}
	return nil
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// recv_wall and send_wall are the peer's physical clock when the
	// request arrived and when the reply left.
	RecvWall      int64 `protobuf:"varint,1,opt,name=recv_wall,json=recvWall,proto3" json:"recv_wall,omitempty"`
	SendWall      int64 `protobuf:"varint,2,opt,name=send_wall,json=sendWall,proto3" json:"send_wall,omitempty"`
	Now           *Hlc  `protobuf:"bytes,3,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_datax_v1_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetRecvWall() int64 {
	if x != nil {
		return x.RecvWall
	}
	return 0
}

func (x *PingResponse) GetSendWall() int64 {
	if x != nil {
		return x.SendWall
	}
	return 0
}

func (x *PingResponse) GetNow() *Hlc {
	if x != nil {
		return x.Now
	}
	return nil
}

// Hlc carries an HLC reading; every message type embeds one so receivers can
// ratchet their clocks (see docs/transactions.md).
type Hlc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WallTime      int64                  `protobuf:"varint,1,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	Logical       int32                  `protobuf:"varint,2,opt,name=logical,proto3" json:"logical,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hlc) Reset() {
	*x = Hlc{}
	mi := &file_datax_v1_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hlc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hlc) ProtoMessage() {}

func (x *Hlc) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hlc.ProtoReflect.Descriptor instead.
func (*Hlc) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{2}
}

func (x *Hlc) GetWallTime() int64 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

func (x *Hlc) GetLogical() int32 {
	if x != nil {
		return x.Logical
	}
	return 0
}

type RaftEnvelope struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RangeId     int64                  `protobuf:"varint,1,opt,name=range_id,json=rangeId,proto3" json:"range_id,omitempty"`
	ToReplica   uint64                 `protobuf:"varint,2,opt,name=to_replica,json=toReplica,proto3" json:"to_replica,omitempty"`
	FromReplica uint64                 `protobuf:"varint,3,opt,name=from_replica,json=fromReplica,proto3" json:"from_replica,omitempty"`
	FromNode    int32                  `protobuf:"varint,4,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	Message     []byte                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"` // marshaled raftpb.Message
	Now         *Hlc                   `protobuf:"bytes,6,opt,name=now,proto3" json:"now,omitempty"`
	// The sender's RPC address: receivers learn peer addresses from Raft
	// traffic itself, so elections never depend on reading the (possibly
	// leaderless) registry range.
	FromAddr string `protobuf:"bytes,7,opt,name=from_addr,json=fromAddr,proto3" json:"from_addr,omitempty"`
	// The sender's storage-health snapshot, piggybacked so leaders can factor
	// follower health into their write path with no extra traffic. Old
	// receivers ignore the field (benign — they just keep leader-only
	// backpressure).
	Health *StorageHealth `protobuf:"bytes,8,opt,name=health,proto3" json:"health,omitempty"`
	// Coalesced heartbeats (cluster version v12): every leader heartbeat
	// and follower response this node had for the receiver since its last
	// envelope, one entry per range instead of one envelope each; message
	// is empty then and the receiver fans them out to its replicas.
	Heartbeats         []*RaftHeartbeat `protobuf:"bytes,9,rep,name=heartbeats,proto3" json:"heartbeats,omitempty"`
	HeartbeatResponses []*RaftHeartbeat `protobuf:"bytes,10,rep,name=heartbeat_responses,json=heartbeatResponses,proto3" json:"heartbeat_responses,omitempty"`
	// Closed-timestamp updates for quiescent ranges: the leader's promise
	// that nothing at or below closed will commit, valid on a follower that
	// still follows (from_replica, term) and has applied index.
	ClosedTimestamps []*RaftHeartbeat `protobuf:"bytes,11,rep,name=closed_timestamps,json=closedTimestamps,proto3" json:"closed_timestamps,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RaftEnvelope) Reset() {
	*x = RaftEnvelope{}
	mi := &file_datax_v1_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftEnvelope) ProtoMessage() {}

func (x *RaftEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftEnvelope.ProtoReflect.Descriptor instead.
func (*RaftEnvelope) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{3}
}

func (x *RaftEnvelope) GetRangeId() int64 {
	if x != nil {
		return x.RangeId
	}
	return 0
}

func (x *RaftEnvelope) GetToReplica() uint64 {
	if x != nil {
		return x.ToReplica
	}
	return 0
}

func (x *RaftEnvelope) GetFromReplica() uint64 {
	if x != nil {
		return x.FromReplica
	}
	return 0
}

func (x *RaftEnvelope) GetFromNode() int32 {
	if x != nil {
		return x.FromNode
	}
	return 0
}

func (x *RaftEnvelope) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RaftEnvelope) GetNow() *Hlc {
	if x != nil {
		return x.Now
	}
	return nil
}

func (x *RaftEnvelope) GetFromAddr() string {
	if x != nil {
		return x.FromAddr
	}
	return ""
}

func (x *RaftEnvelope) GetHealth() *StorageHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *RaftEnvelope) GetHeartbeats() []*RaftHeartbeat {
	if x != nil {
		return x.Heartbeats
	}
	return nil
}

func (x *RaftEnvelope) GetHeartbeatResponses() []*RaftHeartbeat {
	if x != nil {
		return x.HeartbeatResponses
	}
	return nil
}

func (x *RaftEnvelope) GetClosedTimestamps() []*RaftHeartbeat {
	if x != nil {
		return x.ClosedTimestamps
	}
	return nil
}

// RaftHeartbeat is one range's MsgHeartbeat or MsgHeartbeatResp, reduced
// to the fields raft reads from them.
type RaftHeartbeat struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RangeId     int64                  `protobuf:"varint,1,opt,name=range_id,json=rangeId,proto3" json:"range_id,omitempty"`
	ToReplica   uint64                 `protobuf:"varint,2,opt,name=to_replica,json=toReplica,proto3" json:"to_replica,omitempty"`
	FromReplica uint64                 `protobuf:"varint,3,opt,name=from_replica,json=fromReplica,proto3" json:"from_replica,omitempty"`
	Term        uint64                 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	Commit      uint64                 `protobuf:"varint,5,opt,name=commit,proto3" json:"commit,omitempty"`
	// quiesce: the leader is going idle (every follower holds every entry
	// and nothing is pending); a follower that holds commit quiesces too —
	// stops ticking, so no election timer runs — until the next message
	// or request wakes it.
	Quiesce bool `protobuf:"varint,6,opt,name=quiesce,proto3" json:"quiesce,omitempty"`
	// Closed-timestamp updates only: the leader's last log index when the
	// promise was made and the closed timestamp itself.
	Index         uint64 `protobuf:"varint,7,opt,name=index,proto3" json:"index,omitempty"`
	ClosedWall    int64  `protobuf:"varint,8,opt,name=closed_wall,json=closedWall,proto3" json:"closed_wall,omitempty"`
	ClosedLogical int32  `protobuf:"varint,9,opt,name=closed_logical,json=closedLogical,proto3" json:"closed_logical,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftHeartbeat) Reset() {
	*x = RaftHeartbeat{}
	mi := &file_datax_v1_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftHeartbeat) ProtoMessage() {}

func (x *RaftHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftHeartbeat.ProtoReflect.Descriptor instead.
func (*RaftHeartbeat) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{4}
}

func (x *RaftHeartbeat) GetRangeId() int64 {
	if x != nil {
		return x.RangeId
	}
	return 0
}

func (x *RaftHeartbeat) GetToReplica() uint64 {
	if x != nil {
		return x.ToReplica
	}
	return 0
}

func (x *RaftHeartbeat) GetFromReplica() uint64 {
	if x != nil {
		return x.FromReplica
	}
	return 0
}

func (x *RaftHeartbeat) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftHeartbeat) GetCommit() uint64 {
	if x != nil {
		return x.Commit
	}
	return 0
}

func (x *RaftHeartbeat) GetQuiesce() bool {
	if x != nil {
		return x.Quiesce
	}
	return false
}

func (x *RaftHeartbeat) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RaftHeartbeat) GetClosedWall() int64 {
	if x != nil {
		return x.ClosedWall
	}
	return 0
}

func (x *RaftHeartbeat) GetClosedLogical() int32 {
	if x != nil {
		return x.ClosedLogical
	}
	return 0
}

// StorageHealth is a node's storage-health snapshot. `overloaded` is the
// sender's own soft-gate verdict against its storage profile (the numbers
// are advisory detail — the receiver never re-judges them, so profiles
// stay a per-node concern).
type StorageHealth struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Overloaded          bool                   `protobuf:"varint,1,opt,name=overloaded,proto3" json:"overloaded,omitempty"`
	Reason              string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	L0Sublevels         int64                  `protobuf:"varint,3,opt,name=l0_sublevels,json=l0Sublevels,proto3" json:"l0_sublevels,omitempty"`
	L0Files             int64                  `protobuf:"varint,4,opt,name=l0_files,json=l0Files,proto3" json:"l0_files,omitempty"`
	CompactionDebtBytes int64                  `protobuf:"varint,5,opt,name=compaction_debt_bytes,json=compactionDebtBytes,proto3" json:"compaction_debt_bytes,omitempty"`
	MemtableBytes       int64                  `protobuf:"varint,6,opt,name=memtable_bytes,json=memtableBytes,proto3" json:"memtable_bytes,omitempty"`
	// wall_time was the sender's wall clock. Receivers stamp a verdict with
	// their own receipt time instead (clocks need not agree), so senders
	// leave it zero; the field number stays reserved for wire compatibility.
	WallTime      int64 `protobuf:"varint,7,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageHealth) Reset() {
	*x = StorageHealth{}
	mi := &file_datax_v1_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageHealth) ProtoMessage() {}

func (x *StorageHealth) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageHealth.ProtoReflect.Descriptor instead.
func (*StorageHealth) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{5}
}

func (x *StorageHealth) GetOverloaded() bool {
	if x != nil {
		return x.Overloaded
	}
	return false
}

func (x *StorageHealth) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StorageHealth) GetL0Sublevels() int64 {
	if x != nil {
		return x.L0Sublevels
	}
	return 0
}

func (x *StorageHealth) GetL0Files() int64 {
	if x != nil {
		return x.L0Files
	}
	return 0
}

func (x *StorageHealth) GetCompactionDebtBytes() int64 {
	if x != nil {
		return x.CompactionDebtBytes
	}
	return 0
}

func (x *StorageHealth) GetMemtableBytes() int64 {
	if x != nil {
		return x.MemtableBytes
	}
	return 0
}

func (x *StorageHealth) GetWallTime() int64 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

type RaftAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftAck) Reset() {
	*x = RaftAck{}
	mi := &file_datax_v1_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAck) ProtoMessage() {}

func (x *RaftAck) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAck.ProtoReflect.Descriptor instead.
func (*RaftAck) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{6}
}

type Payload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Json  []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	Now   *Hlc                   `protobuf:"bytes,2,opt,name=now,proto3" json:"now,omitempty"`
	// proto carries a binary body on hot paths (Batch: BatchRequest out,
	// BatchEnvelope back — see kv.proto). Exactly one of json/proto is set;
	// receivers dispatch on which. Cold paths (join/admin) stay JSON.
	Proto         []byte `protobuf:"bytes,3,opt,name=proto,proto3" json:"proto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_datax_v1_transport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{7}
}

func (x *Payload) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

func (x *Payload) GetNow() *Hlc {
	if x != nil {
		return x.Now
	}
	return nil
}

func (x *Payload) GetProto() []byte {
	if x != nil {
		return x.Proto
	}
	return nil
}

type SnapshotChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First chunk carries the JSON header (range descriptor, applied index);
	// subsequent chunks carry raw key/value data.
	HeaderJson    []byte        `protobuf:"bytes,1,opt,name=header_json,json=headerJson,proto3" json:"header_json,omitempty"`
	Kvs           []*SnapshotKV `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
	Now           *Hlc          `protobuf:"bytes,3,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotChunk) Reset() {
	*x = SnapshotChunk{}
	mi := &file_datax_v1_transport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotChunk) ProtoMessage() {}

func (x *SnapshotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotChunk.ProtoReflect.Descriptor instead.
func (*SnapshotChunk) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{8}
}

func (x *SnapshotChunk) GetHeaderJson() []byte {
	if x != nil {
		return x.HeaderJson
	}
	return nil
}

func (x *SnapshotChunk) GetKvs() []*SnapshotKV {
	if x != nil {
		return x.Kvs
	}
	return nil
}

func (x *SnapshotChunk) GetNow() *Hlc {
	if x != nil {
		return x.Now
	}
	return nil
}

type SnapshotKV struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotKV) Reset() {
	*x = SnapshotKV{}
	mi := &file_datax_v1_transport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotKV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotKV) ProtoMessage() {}

func (x *SnapshotKV) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotKV.ProtoReflect.Descriptor instead.
func (*SnapshotKV) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{9}
}

func (x *SnapshotKV) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SnapshotKV) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SnapshotAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotAck) Reset() {
	*x = SnapshotAck{}
	mi := &file_datax_v1_transport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotAck) ProtoMessage() {}

func (x *SnapshotAck) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotAck.ProtoReflect.Descriptor instead.
func (*SnapshotAck) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{10}
}

var File_datax_v1_transport_proto protoreflect.FileDescriptor

const file_datax_v1_transport_proto_rawDesc = "" +
	"\n" +
	"\x18datax/v1/transport.proto\x12\bdatax.v1\"h\n" +
	"\vPingRequest\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\x03R\bfromNode\x12\x1b\n" +
	"\tsend_wall\x18\x02 \x01(\x03R\bsendWall\x12\x1f\n" +
	"\x03now\x18\x03 \x01(\v2\r.datax.v1.HlcR\x03now\"i\n" +
	"\fPingResponse\x12\x1b\n" +
	"\trecv_wall\x18\x01 \x01(\x03R\brecvWall\x12\x1b\n" +
	"\tsend_wall\x18\x02 \x01(\x03R\bsendWall\x12\x1f\n" +
	"\x03now\x18\x03 \x01(\v2\r.datax.v1.HlcR\x03now\"<\n" +
	"\x03Hlc\x12\x1b\n" +
	"\twall_time\x18\x01 \x01(\x03R\bwallTime\x12\x18\n" +
	"\alogical\x18\x02 \x01(\x05R\alogical\"\xda\x03\n" +
	"\fRaftEnvelope\x12\x19\n" +
	"\brange_id\x18\x01 \x01(\x03R\arangeId\x12\x1d\n" +
	"\n" +
	"to_replica\x18\x02 \x01(\x04R\ttoReplica\x12!\n" +
	"\ffrom_replica\x18\x03 \x01(\x04R\vfromReplica\x12\x1b\n" +
	"\tfrom_node\x18\x04 \x01(\x05R\bfromNode\x12\x18\n" +
	"\amessage\x18\x05 \x01(\fR\amessage\x12\x1f\n" +
	"\x03now\x18\x06 \x01(\v2\r.datax.v1.HlcR\x03now\x12\x1b\n" +
	"\tfrom_addr\x18\a \x01(\tR\bfromAddr\x12/\n" +
	"\x06health\x18\b \x01(\v2\x17.datax.v1.StorageHealthR\x06health\x127\n" +
	"\n" +
	"heartbeats\x18\t \x03(\v2\x17.datax.v1.RaftHeartbeatR\n" +
	"heartbeats\x12H\n" +
	"\x13heartbeat_responses\x18\n" +
	" \x03(\v2\x17.datax.v1.RaftHeartbeatR\x12heartbeatResponses\x12D\n" +
	"\x11closed_timestamps\x18\v \x03(\v2\x17.datax.v1.RaftHeartbeatR\x10closedTimestamps\"\x90\x02\n" +
	"\rRaftHeartbeat\x12\x19\n" +
	"\brange_id\x18\x01 \x01(\x03R\arangeId\x12\x1d\n" +
	"\n" +
	"to_replica\x18\x02 \x01(\x04R\ttoReplica\x12!\n" +
	"\ffrom_replica\x18\x03 \x01(\x04R\vfromReplica\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term\x12\x16\n" +
	"\x06commit\x18\x05 \x01(\x04R\x06commit\x12\x18\n" +
	"\aquiesce\x18\x06 \x01(\bR\aquiesce\x12\x14\n" +
	"\x05index\x18\a \x01(\x04R\x05index\x12\x1f\n" +
	"\vclosed_wall\x18\b \x01(\x03R\n" +
	"closedWall\x12%\n" +
	"\x0eclosed_logical\x18\t \x01(\x05R\rclosedLogical\"\xfd\x01\n" +
	"\rStorageHealth\x12\x1e\n" +
	"\n" +
	"overloaded\x18\x01 \x01(\bR\n" +
	"overloaded\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12!\n" +
	"\fl0_sublevels\x18\x03 \x01(\x03R\vl0Sublevels\x12\x19\n" +
	"\bl0_files\x18\x04 \x01(\x03R\al0Files\x122\n" +
	"\x15compaction_debt_bytes\x18\x05 \x01(\x03R\x13compactionDebtBytes\x12%\n" +
	"\x0ememtable_bytes\x18\x06 \x01(\x03R\rmemtableBytes\x12\x1b\n" +
	"\twall_time\x18\a \x01(\x03R\bwallTime\"\t\n" +
	"\aRaftAck\"T\n" +
	"\aPayload\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\x12\x1f\n" +
	"\x03now\x18\x02 \x01(\v2\r.datax.v1.HlcR\x03now\x12\x14\n" +
	"\x05proto\x18\x03 \x01(\fR\x05proto\"y\n" +
	"\rSnapshotChunk\x12\x1f\n" +
	"\vheader_json\x18\x01 \x01(\fR\n" +
	"headerJson\x12&\n" +
	"\x03kvs\x18\x02 \x03(\v2\x14.datax.v1.SnapshotKVR\x03kvs\x12\x1f\n" +
	"\x03now\x18\x03 \x01(\v2\r.datax.v1.HlcR\x03now\"4\n" +
	"\n" +
	"SnapshotKV\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\r\n" +
	"\vSnapshotAck2\xc9\x02\n" +
	"\tInternode\x12;\n" +
	"\fRaftMessages\x12\x16.datax.v1.RaftEnvelope\x1a\x11.datax.v1.RaftAck(\x01\x12-\n" +
	"\x05Batch\x12\x11.datax.v1.Payload\x1a\x11.datax.v1.Payload\x12,\n" +
	"\x04Join\x12\x11.datax.v1.Payload\x1a\x11.datax.v1.Payload\x12-\n" +
	"\x05Admin\x12\x11.datax.v1.Payload\x1a\x11.datax.v1.Payload\x12<\n" +
	"\bSnapshot\x12\x17.datax.v1.SnapshotChunk\x1a\x15.datax.v1.SnapshotAck(\x01\x125\n" +
	"\x04Ping\x12\x15.datax.v1.PingRequest\x1a\x16.datax.v1.PingResponseB(Z&github.com/sthorne/datax/pkg/rpc/rpcpbb\x06proto3"

var (
	file_datax_v1_transport_proto_rawDescOnce sync.Once
	file_datax_v1_transport_proto_rawDescData []byte
)

func file_datax_v1_transport_proto_rawDescGZIP() []byte {
	file_datax_v1_transport_proto_rawDescOnce.Do(func() {
		file_datax_v1_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datax_v1_transport_proto_rawDesc), len(file_datax_v1_transport_proto_rawDesc)))
	})
	return file_datax_v1_transport_proto_rawDescData
}

var file_datax_v1_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_datax_v1_transport_proto_goTypes = []any{
	(*PingRequest)(nil),   // 0: datax.v1.PingRequest
	(*PingResponse)(nil),  // 1: datax.v1.PingResponse
	(*Hlc)(nil),           // 2: datax.v1.Hlc
	(*RaftEnvelope)(nil),  // 3: datax.v1.RaftEnvelope
	(*RaftHeartbeat)(nil), // 4: datax.v1.RaftHeartbeat
	(*StorageHealth)(nil), // 5: datax.v1.StorageHealth
	(*RaftAck)(nil),       // 6: datax.v1.RaftAck
	(*Payload)(nil),       // 7: datax.v1.Payload
	(*SnapshotChunk)(nil), // 8: datax.v1.SnapshotChunk
	(*SnapshotKV)(nil),    // 9: datax.v1.SnapshotKV
	(*SnapshotAck)(nil),   // 10: datax.v1.SnapshotAck
}
var file_datax_v1_transport_proto_depIdxs = []int32{
	2,  // 0: datax.v1.PingRequest.now:type_name -> datax.v1.Hlc
	2,  // 1: datax.v1.PingResponse.now:type_name -> datax.v1.Hlc
	2,  // 2: datax.v1.RaftEnvelope.now:type_name -> datax.v1.Hlc
	5,  // 3: datax.v1.RaftEnvelope.health:type_name -> datax.v1.StorageHealth
	4,  // 4: datax.v1.RaftEnvelope.heartbeats:type_name -> datax.v1.RaftHeartbeat
	4,  // 5: datax.v1.RaftEnvelope.heartbeat_responses:type_name -> datax.v1.RaftHeartbeat
	4,  // 6: datax.v1.RaftEnvelope.closed_timestamps:type_name -> datax.v1.RaftHeartbeat
	2,  // 7: datax.v1.Payload.now:type_name -> datax.v1.Hlc
	9,  // 8: datax.v1.SnapshotChunk.kvs:type_name -> datax.v1.SnapshotKV
	2,  // 9: datax.v1.SnapshotChunk.now:type_name -> datax.v1.Hlc
	3,  // 10: datax.v1.Internode.RaftMessages:input_type -> datax.v1.RaftEnvelope
	7,  // 11: datax.v1.Internode.Batch:input_type -> datax.v1.Payload
	7,  // 12: datax.v1.Internode.Join:input_type -> datax.v1.Payload
	7,  // 13: datax.v1.Internode.Admin:input_type -> datax.v1.Payload
	8,  // 14: datax.v1.Internode.Snapshot:input_type -> datax.v1.SnapshotChunk
	0,  // 15: datax.v1.Internode.Ping:input_type -> datax.v1.PingRequest
	6,  // 16: datax.v1.Internode.RaftMessages:output_type -> datax.v1.RaftAck
	7,  // 17: datax.v1.Internode.Batch:output_type -> datax.v1.Payload
	7,  // 18: datax.v1.Internode.Join:output_type -> datax.v1.Payload
	7,  // 19: datax.v1.Internode.Admin:output_type -> datax.v1.Payload
	10, // 20: datax.v1.Internode.Snapshot:output_type -> datax.v1.SnapshotAck
	1,  // 21: datax.v1.Internode.Ping:output_type -> datax.v1.PingResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_datax_v1_transport_proto_init() }
func file_datax_v1_transport_proto_init() {
	if File_datax_v1_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datax_v1_transport_proto_rawDesc), len(file_datax_v1_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datax_v1_transport_proto_goTypes,
		DependencyIndexes: file_datax_v1_transport_proto_depIdxs,
		MessageInfos:      file_datax_v1_transport_proto_msgTypes,
	}.Build()
	File_datax_v1_transport_proto = out.File
	file_datax_v1_transport_proto_goTypes = nil
	file_datax_v1_transport_proto_depIdxs = nil
}
