// The datax internode transport: Raft messages, KV batches, cluster
// membership, and admin operations. Payload bodies for KV/join/admin are
// JSON-encoded Go types from pkg/kvpb and pkg/cluster (see those packages);
// Raft messages are raftpb.Message bytes, opaque to the transport.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: datax/v1/transport.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Hlc carries an HLC reading; every message type embeds one so receivers can
// ratchet their clocks (see docs/transactions.md).
type Hlc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WallTime      int64                  `protobuf:"varint,1,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	Logical       int32                  `protobuf:"varint,2,opt,name=logical,proto3" json:"logical,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hlc) Reset() {
	*x = Hlc{}
	mi := &file_datax_v1_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hlc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hlc) ProtoMessage() {}

func (x *Hlc) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hlc.ProtoReflect.Descriptor instead.
func (*Hlc) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Hlc) GetWallTime() int64 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

func (x *Hlc) GetLogical() int32 {
	if x != nil {
		return x.Logical
	}
	return 0
}

type RaftEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RangeId       int64                  `protobuf:"varint,1,opt,name=range_id,json=rangeId,proto3" json:"range_id,omitempty"`
	ToReplica     uint64                 `protobuf:"varint,2,opt,name=to_replica,json=toReplica,proto3" json:"to_replica,omitempty"`
	FromReplica   uint64                 `protobuf:"varint,3,opt,name=from_replica,json=fromReplica,proto3" json:"from_replica,omitempty"`
	FromNode      int32                  `protobuf:"varint,4,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	Message       []byte                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"` // marshaled raftpb.Message
	Now           *Hlc                   `protobuf:"bytes,6,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftEnvelope) Reset() {
	*x = RaftEnvelope{}
	mi := &file_datax_v1_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftEnvelope) ProtoMessage() {}

func (x *RaftEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftEnvelope.ProtoReflect.Descriptor instead.
func (*RaftEnvelope) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{1}
}

func (x *RaftEnvelope) GetRangeId() int64 {
	if x != nil {
		return x.RangeId
	}
	return 0
}

func (x *RaftEnvelope) GetToReplica() uint64 {
	if x != nil {
		return x.ToReplica
	}
	return 0
}

func (x *RaftEnvelope) GetFromReplica() uint64 {
	if x != nil {
		return x.FromReplica
	}
	return 0
}

func (x *RaftEnvelope) GetFromNode() int32 {
	if x != nil {
		return x.FromNode
	}
	return 0
}

func (x *RaftEnvelope) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RaftEnvelope) GetNow() *Hlc {
	if x != nil {
		return x.Now
	}
	return nil
}

type RaftAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftAck) Reset() {
	*x = RaftAck{}
	mi := &file_datax_v1_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAck) ProtoMessage() {}

func (x *RaftAck) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAck.ProtoReflect.Descriptor instead.
func (*RaftAck) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{2}
}

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	Now           *Hlc                   `protobuf:"bytes,2,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_datax_v1_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{3}
}

func (x *Payload) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

func (x *Payload) GetNow() *Hlc {
	if x != nil {
		return x.Now
	}
	return nil
}

type SnapshotChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First chunk carries the JSON header (range descriptor, applied index);
	// subsequent chunks carry raw key/value data.
	HeaderJson    []byte        `protobuf:"bytes,1,opt,name=header_json,json=headerJson,proto3" json:"header_json,omitempty"`
	Kvs           []*SnapshotKV `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
	Now           *Hlc          `protobuf:"bytes,3,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotChunk) Reset() {
	*x = SnapshotChunk{}
	mi := &file_datax_v1_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotChunk) ProtoMessage() {}

func (x *SnapshotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotChunk.ProtoReflect.Descriptor instead.
func (*SnapshotChunk) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{4}
}

func (x *SnapshotChunk) GetHeaderJson() []byte {
	if x != nil {
		return x.HeaderJson
	}
	return nil
}

func (x *SnapshotChunk) GetKvs() []*SnapshotKV {
	if x != nil {
		return x.Kvs
	}
	return nil
}

func (x *SnapshotChunk) GetNow() *Hlc {
	if x != nil {
		return x.Now
	}
	return nil
}

type SnapshotKV struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotKV) Reset() {
	*x = SnapshotKV{}
	mi := &file_datax_v1_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotKV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotKV) ProtoMessage() {}

func (x *SnapshotKV) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotKV.ProtoReflect.Descriptor instead.
func (*SnapshotKV) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{5}
}

func (x *SnapshotKV) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SnapshotKV) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SnapshotAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotAck) Reset() {
	*x = SnapshotAck{}
	mi := &file_datax_v1_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotAck) ProtoMessage() {}

func (x *SnapshotAck) ProtoReflect() protoreflect.Message {
	mi := &file_datax_v1_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotAck.ProtoReflect.Descriptor instead.
func (*SnapshotAck) Descriptor() ([]byte, []int) {
	return file_datax_v1_transport_proto_rawDescGZIP(), []int{6}
}

var File_datax_v1_transport_proto protoreflect.FileDescriptor

const file_datax_v1_transport_proto_rawDesc = "" +
	"\n" +
	"\x18datax/v1/transport.proto\x12\bdatax.v1\"<\n" +
	"\x03Hlc\x12\x1b\n" +
	"\twall_time\x18\x01 \x01(\x03R\bwallTime\x12\x18\n" +
	"\alogical\x18\x02 \x01(\x05R\alogical\"\xc3\x01\n" +
	"\fRaftEnvelope\x12\x19\n" +
	"\brange_id\x18\x01 \x01(\x03R\arangeId\x12\x1d\n" +
	"\n" +
	"to_replica\x18\x02 \x01(\x04R\ttoReplica\x12!\n" +
	"\ffrom_replica\x18\x03 \x01(\x04R\vfromReplica\x12\x1b\n" +
	"\tfrom_node\x18\x04 \x01(\x05R\bfromNode\x12\x18\n" +
	"\amessage\x18\x05 \x01(\fR\amessage\x12\x1f\n" +
	"\x03now\x18\x06 \x01(\v2\r.datax.v1.HlcR\x03now\"\t\n" +
	"\aRaftAck\">\n" +
	"\aPayload\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\x12\x1f\n" +
	"\x03now\x18\x02 \x01(\v2\r.datax.v1.HlcR\x03now\"y\n" +
	"\rSnapshotChunk\x12\x1f\n" +
	"\vheader_json\x18\x01 \x01(\fR\n" +
	"headerJson\x12&\n" +
	"\x03kvs\x18\x02 \x03(\v2\x14.datax.v1.SnapshotKVR\x03kvs\x12\x1f\n" +
	"\x03now\x18\x03 \x01(\v2\r.datax.v1.HlcR\x03now\"4\n" +
	"\n" +
	"SnapshotKV\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\r\n" +
	"\vSnapshotAck2\x92\x02\n" +
	"\tInternode\x12;\n" +
	"\fRaftMessages\x12\x16.datax.v1.RaftEnvelope\x1a\x11.datax.v1.RaftAck(\x01\x12-\n" +
	"\x05Batch\x12\x11.datax.v1.Payload\x1a\x11.datax.v1.Payload\x12,\n" +
	"\x04Join\x12\x11.datax.v1.Payload\x1a\x11.datax.v1.Payload\x12-\n" +
	"\x05Admin\x12\x11.datax.v1.Payload\x1a\x11.datax.v1.Payload\x12<\n" +
	"\bSnapshot\x12\x17.datax.v1.SnapshotChunk\x1a\x15.datax.v1.SnapshotAck(\x01B(Z&github.com/sthorne/datax/pkg/rpc/rpcpbb\x06proto3"

var (
	file_datax_v1_transport_proto_rawDescOnce sync.Once
	file_datax_v1_transport_proto_rawDescData []byte
)

func file_datax_v1_transport_proto_rawDescGZIP() []byte {
	file_datax_v1_transport_proto_rawDescOnce.Do(func() {
		file_datax_v1_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datax_v1_transport_proto_rawDesc), len(file_datax_v1_transport_proto_rawDesc)))
	})
	return file_datax_v1_transport_proto_rawDescData
}

var file_datax_v1_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_datax_v1_transport_proto_goTypes = []any{
	(*Hlc)(nil),           // 0: datax.v1.Hlc
	(*RaftEnvelope)(nil),  // 1: datax.v1.RaftEnvelope
	(*RaftAck)(nil),       // 2: datax.v1.RaftAck
	(*Payload)(nil),       // 3: datax.v1.Payload
	(*SnapshotChunk)(nil), // 4: datax.v1.SnapshotChunk
	(*SnapshotKV)(nil),    // 5: datax.v1.SnapshotKV
	(*SnapshotAck)(nil),   // 6: datax.v1.SnapshotAck
}
var file_datax_v1_transport_proto_depIdxs = []int32{
	0, // 0: datax.v1.RaftEnvelope.now:type_name -> datax.v1.Hlc
	0, // 1: datax.v1.Payload.now:type_name -> datax.v1.Hlc
	5, // 2: datax.v1.SnapshotChunk.kvs:type_name -> datax.v1.SnapshotKV
	0, // 3: datax.v1.SnapshotChunk.now:type_name -> datax.v1.Hlc
	1, // 4: datax.v1.Internode.RaftMessages:input_type -> datax.v1.RaftEnvelope
	3, // 5: datax.v1.Internode.Batch:input_type -> datax.v1.Payload
	3, // 6: datax.v1.Internode.Join:input_type -> datax.v1.Payload
	3, // 7: datax.v1.Internode.Admin:input_type -> datax.v1.Payload
	4, // 8: datax.v1.Internode.Snapshot:input_type -> datax.v1.SnapshotChunk
	2, // 9: datax.v1.Internode.RaftMessages:output_type -> datax.v1.RaftAck
	3, // 10: datax.v1.Internode.Batch:output_type -> datax.v1.Payload
	3, // 11: datax.v1.Internode.Join:output_type -> datax.v1.Payload
	3, // 12: datax.v1.Internode.Admin:output_type -> datax.v1.Payload
	6, // 13: datax.v1.Internode.Snapshot:output_type -> datax.v1.SnapshotAck
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_datax_v1_transport_proto_init() }
func file_datax_v1_transport_proto_init() {
	if File_datax_v1_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datax_v1_transport_proto_rawDesc), len(file_datax_v1_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datax_v1_transport_proto_goTypes,
		DependencyIndexes: file_datax_v1_transport_proto_depIdxs,
		MessageInfos:      file_datax_v1_transport_proto_msgTypes,
	}.Build()
	File_datax_v1_transport_proto = out.File
	file_datax_v1_transport_proto_goTypes = nil
	file_datax_v1_transport_proto_depIdxs = nil
}
