// The datax internode transport: Raft messages, KV batches, cluster
// membership, and admin operations. Payload bodies for KV/join/admin are
// JSON-encoded Go types from pkg/kvpb and pkg/cluster (see those packages);
// Raft messages are raftpb.Message bytes, opaque to the transport.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: datax/v1/transport.proto

package rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Internode_RaftMessages_FullMethodName = "/datax.v1.Internode/RaftMessages"
	Internode_Batch_FullMethodName        = "/datax.v1.Internode/Batch"
	Internode_Join_FullMethodName         = "/datax.v1.Internode/Join"
	Internode_Admin_FullMethodName        = "/datax.v1.Internode/Admin"
	Internode_Snapshot_FullMethodName     = "/datax.v1.Internode/Snapshot"
)

// InternodeClient is the client API for Internode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternodeClient interface {
	// RaftMessages is a long-lived, unidirectional stream of Raft messages
	// from one node to another (one stream per node pair, sender-initiated).
	RaftMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RaftEnvelope, RaftAck], error)
	// Batch executes a KV batch (JSON kvpb.BatchRequest / BatchResponse).
	Batch(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Payload, error)
	// Join adds a node to the cluster (JSON cluster.JoinRequest / JoinResponse).
	Join(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Payload, error)
	// Admin executes cluster admin operations (JSON cluster.AdminRequest /
	// AdminResponse): split, rebalance, list ranges/nodes.
	Admin(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Payload, error)
	// Snapshot streams a range snapshot to seed a new replica.
	Snapshot(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SnapshotChunk, SnapshotAck], error)
}

type internodeClient struct {
	cc grpc.ClientConnInterface
}

func NewInternodeClient(cc grpc.ClientConnInterface) InternodeClient {
	return &internodeClient{cc}
}

func (c *internodeClient) RaftMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RaftEnvelope, RaftAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Internode_ServiceDesc.Streams[0], Internode_RaftMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RaftEnvelope, RaftAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Internode_RaftMessagesClient = grpc.ClientStreamingClient[RaftEnvelope, RaftAck]

func (c *internodeClient) Batch(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Payload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Payload)
	err := c.cc.Invoke(ctx, Internode_Batch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internodeClient) Join(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Payload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Payload)
	err := c.cc.Invoke(ctx, Internode_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internodeClient) Admin(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Payload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Payload)
	err := c.cc.Invoke(ctx, Internode_Admin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internodeClient) Snapshot(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SnapshotChunk, SnapshotAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Internode_ServiceDesc.Streams[1], Internode_Snapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapshotChunk, SnapshotAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Internode_SnapshotClient = grpc.ClientStreamingClient[SnapshotChunk, SnapshotAck]

// InternodeServer is the server API for Internode service.
// All implementations must embed UnimplementedInternodeServer
// for forward compatibility.
type InternodeServer interface {
	// RaftMessages is a long-lived, unidirectional stream of Raft messages
	// from one node to another (one stream per node pair, sender-initiated).
	RaftMessages(grpc.ClientStreamingServer[RaftEnvelope, RaftAck]) error
	// Batch executes a KV batch (JSON kvpb.BatchRequest / BatchResponse).
	Batch(context.Context, *Payload) (*Payload, error)
	// Join adds a node to the cluster (JSON cluster.JoinRequest / JoinResponse).
	Join(context.Context, *Payload) (*Payload, error)
	// Admin executes cluster admin operations (JSON cluster.AdminRequest /
	// AdminResponse): split, rebalance, list ranges/nodes.
	Admin(context.Context, *Payload) (*Payload, error)
	// Snapshot streams a range snapshot to seed a new replica.
	Snapshot(grpc.ClientStreamingServer[SnapshotChunk, SnapshotAck]) error
	mustEmbedUnimplementedInternodeServer()
}

// UnimplementedInternodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternodeServer struct{}

func (UnimplementedInternodeServer) RaftMessages(grpc.ClientStreamingServer[RaftEnvelope, RaftAck]) error {
	return status.Errorf(codes.Unimplemented, "method RaftMessages not implemented")
}
func (UnimplementedInternodeServer) Batch(context.Context, *Payload) (*Payload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Batch not implemented")
}
func (UnimplementedInternodeServer) Join(context.Context, *Payload) (*Payload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedInternodeServer) Admin(context.Context, *Payload) (*Payload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Admin not implemented")
}
func (UnimplementedInternodeServer) Snapshot(grpc.ClientStreamingServer[SnapshotChunk, SnapshotAck]) error {
	return status.Errorf(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedInternodeServer) mustEmbedUnimplementedInternodeServer() {}
func (UnimplementedInternodeServer) testEmbeddedByValue()                   {}

// UnsafeInternodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternodeServer will
// result in compilation errors.
type UnsafeInternodeServer interface {
	mustEmbedUnimplementedInternodeServer()
}

func RegisterInternodeServer(s grpc.ServiceRegistrar, srv InternodeServer) {
	// If the following call pancis, it indicates UnimplementedInternodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Internode_ServiceDesc, srv)
}

func _Internode_RaftMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InternodeServer).RaftMessages(&grpc.GenericServerStream[RaftEnvelope, RaftAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Internode_RaftMessagesServer = grpc.ClientStreamingServer[RaftEnvelope, RaftAck]

func _Internode_Batch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Payload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternodeServer).Batch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internode_Batch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternodeServer).Batch(ctx, req.(*Payload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internode_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Payload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternodeServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internode_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternodeServer).Join(ctx, req.(*Payload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internode_Admin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Payload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternodeServer).Admin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internode_Admin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternodeServer).Admin(ctx, req.(*Payload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internode_Snapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InternodeServer).Snapshot(&grpc.GenericServerStream[SnapshotChunk, SnapshotAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Internode_SnapshotServer = grpc.ClientStreamingServer[SnapshotChunk, SnapshotAck]

// Internode_ServiceDesc is the grpc.ServiceDesc for Internode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Internode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datax.v1.Internode",
	HandlerType: (*InternodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Batch",
			Handler:    _Internode_Batch_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _Internode_Join_Handler,
		},
		{
			MethodName: "Admin",
			Handler:    _Internode_Admin_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RaftMessages",
			Handler:       _Internode_RaftMessages_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Snapshot",
			Handler:       _Internode_Snapshot_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "datax/v1/transport.proto",
}
